
#ifndef __DICTIONNARY_HEADER__
#define __DICTIONNARY_HEADER__

// Events
#define DICT_LOG_TLM_NOT_UPDATED 0x2
#define DICT_LOG_OpCodeRegistered 0x3
#define DICT_LOG_OpCodeDispatched 0x4
#define DICT_LOG_OpCodeCompleted 0x5
#define DICT_LOG_OpCodeError 0x6
#define DICT_LOG_MalformedCommand 0x7
#define DICT_LOG_InvalidCommand 0x8
#define DICT_LOG_TooManyCommands 0x9
#define DICT_LOG_NoOpReceived 0xa
#define DICT_LOG_NoOpStringReceived 0xb
#define DICT_LOG_TestCmd1Args 0xc
#define DICT_LOG_AF_ASSERT_0 0x15
#define DICT_LOG_AF_ASSERT_1 0x16
#define DICT_LOG_AF_ASSERT_2 0x17
#define DICT_LOG_AF_ASSERT_3 0x18
#define DICT_LOG_AF_ASSERT_4 0x19
#define DICT_LOG_AF_ASSERT_5 0x1a
#define DICT_LOG_AF_ASSERT_6 0x1b
#define DICT_LOG_AF_UNEXPECTED_ASSERT 0x1c
#define DICT_LOG_HLTH_PING_WARN 0x1d
#define DICT_LOG_HLTH_PING_LATE 0x1e
#define DICT_LOG_HLTH_PING_WRONG_KEY 0x1f
#define DICT_LOG_HLTH_CHECK_ENABLE 0x20
#define DICT_LOG_HLTH_CHECK_PING 0x21
#define DICT_LOG_HLTH_CHECK_LOOKUP_ERROR 0x22
#define DICT_LOG_HLTH_PING_UPDATED 0x23
#define DICT_LOG_HLTH_PING_INVALID_VALUES 0x24
#define DICT_LOG_GroundInterfaceError 0x25
#define DICT_LOG_SEVERITY_FILTER_STATE 0x26
#define DICT_LOG_ID_FILTER_ENABLED 0x27
#define DICT_LOG_ID_FILTER_LIST_FULL 0x28
#define DICT_LOG_ID_FILTER_REMOVED 0x29
#define DICT_LOG_ID_FILTER_NOT_FOUND 0x2a
#define DICT_LOG_RateGroup1Started 0x45
#define DICT_LOG_RateGroup1CycleSlip 0x46
#define DICT_LOG_RateGroup2Started 0x47
#define DICT_LOG_RateGroup2CycleSlip 0x48
#define DICT_LOG_RateGroup3Started 0x49
#define DICT_LOG_RateGroup3CycleSlip 0x4a
#define DICT_LOG_RateGroup4Started 0xd2
#define DICT_LOG_RateGroup4CycleSlip 0xd3
#define DICT_LOG_PR_PingsDisabled 0x4c
#define DICT_LOG_PR_PingReceived 0x4d
#define DICT_LOG_DR1_OpenError 0x4f
#define DICT_LOG_DR1_ConfigError 0x50
#define DICT_LOG_DR1_WriteError 0x51
#define DICT_LOG_DR1_ReadError 0x52
#define DICT_LOG_DR1_PortOpened 0x53
#define DICT_LOG_DR1_NoBuffers 0x54
#define DICT_LOG_DR1_BufferTooSmall 0x55
#define DICT_LOG_DR2_OpenError 0x59
#define DICT_LOG_DR2_ConfigError 0x5a
#define DICT_LOG_DR2_WriteError 0x5b
#define DICT_LOG_DR2_ReadError 0x5c
#define DICT_LOG_DR2_PortOpened 0x5d
#define DICT_LOG_DR2_NoBuffers 0x5e
#define DICT_LOG_DR2_BufferTooSmall 0x5f
#define DICT_LOG_Eps_LowBattery 0x64
#define DICT_LOG_Eps_CriticallyLowBattery 0x65
#define DICT_LOG_FT_Mode 0x6e
#define DICT_LOG_FT_Frequency 0x6f
#define DICT_LOG_Gps_LockState 0x78
#define DICT_LOG_PiCam_PictureTaken 0x82
#define DICT_LOG_PiCam_PositionUpdate 0x83
#define DICT_LOG_PiCam_BarometerDataUpdate 0x84
#define DICT_LOG_PiCam_PictureError 0x85
#define DICT_LOG_PiCam_SetTimeInterval 0x86
#define DICT_LOG_PiCam_SetPictureSize 0x87
#define DICT_LOG_Predi_FlightMode 0x8c
#define DICT_LOG_RckBlck_CSQ 0x96
#define DICT_LOG_RckBlck_MessageReceived 0x97
#define DICT_LOG_RckBlck_NoMessageReceived 0x98
#define DICT_LOG_RckBlck_UnableToSend 0x99
#define DICT_LOG_RckBlck_MailboxCheckFail 0x9a
#define DICT_LOG_RckBlck_RingAlert 0x9b
#define DICT_LOG_RckBlck_CommandSent 0x9c
#define DICT_LOG_RckBlck_Response 0x9d
#define DICT_LOG_TempPro_LowInternalWarning 0xa0
#define DICT_LOG_TempPro_LowExternalWarning 0xa1

// Telemetry channels
#define DICT_TLM_CommandsDispatched 0x3
#define DICT_TLM_CommandErrors 0x4
#define DICT_TLM_PingLateWarnings 0x1d
#define DICT_TLM_Rg1MaxTime 0x45
#define DICT_TLM_Rg1CycleSlips 0x46
#define DICT_TLM_Rg2MaxTime 0x47
#define DICT_TLM_Rg2CycleSlips 0x48
#define DICT_TLM_Rg3MaxTime 0x49
#define DICT_TLM_Rg3CycleSlips 0x4a
#define DICT_TLM_Rg4MaxTime 0xd2
#define DICT_TLM_Rg4CycleSlips 0xd3
#define DICT_TLM_PR_NumPings 0x4c
#define DICT_TLM_BD_Cycles 0x4e
#define DICT_TLM_DR1_BytesSent 0x4f
#define DICT_TLM_DR1_BytesRecv 0x50
#define DICT_TLM_DR2_BytesSent 0x59
#define DICT_TLM_DR2_BytesRecv 0x5a
#define DICT_TLM_Eps_BatteryVoltage 0x64
#define DICT_TLM_FT_SSDVBufferLength 0x6e
#define DICT_TLM_Gps_Position 0x78
#define DICT_TLM_Gps_LockState 0x79
#define DICT_TLM_PiCam_PictureCnt 0x82
#define DICT_TLM_PiCam_PictureSize 0x83
#define DICT_TLM_PiCam_Timeinterval 0x84
#define DICT_TLM_Predi_LandingPosition 0x8c
#define DICT_TLM_RckBlck_RSSI 0x96
#define DICT_TLM_TempProb_InternalTemperature 0xa0
#define DICT_TLM_TempProb_ExternalTemperature 0xa1
#define DICT_TLM_THERMOMETER_TEMP 0xb4
#define DICT_TLM_THERMOMETER_HUMI 0xb5
#define DICT_TLM_MOTIONTRACKING_ANGLES 0xbe
#define DICT_TLM_MOTIONTRACKING_GYRO 0xbf
#define DICT_TLM_MOTIONTRACKING_ACCEL 0xc0
#define DICT_TLM_MOTIONTRACKING_MAGN 0xc1
#define DICT_TLM_BAROMETER_TEMP 0xc8
#define DICT_TLM_BAROMETER_PRESS 0xc9
#define DICT_TLM_BAROMETER_ALT 0xca

#endif
