
#ifndef __DICTIONNARY_HEADER__
#define __DICTIONNARY_HEADER__

// Events
#define DICT_TLM_NOT_UPDATED 0x2
#define DICT_OpCodeRegistered 0x3
#define DICT_OpCodeDispatched 0x4
#define DICT_OpCodeCompleted 0x5
#define DICT_OpCodeError 0x6
#define DICT_MalformedCommand 0x7
#define DICT_InvalidCommand 0x8
#define DICT_TooManyCommands 0x9
#define DICT_NoOpReceived 0xa
#define DICT_NoOpStringReceived 0xb
#define DICT_TestCmd1Args 0xc
#define DICT_PrmIdNotFound 0xd
#define DICT_PrmIdUpdated 0xe
#define DICT_PrmDbFull 0xf
#define DICT_PrmIdAdded 0x10
#define DICT_PrmFileWriteError 0x11
#define DICT_PrmFileSaveComplete 0x12
#define DICT_PrmFileReadError 0x13
#define DICT_PrmFileLoadComplete 0x14
#define DICT_AF_ASSERT_0 0x15
#define DICT_AF_ASSERT_1 0x16
#define DICT_AF_ASSERT_2 0x17
#define DICT_AF_ASSERT_3 0x18
#define DICT_AF_ASSERT_4 0x19
#define DICT_AF_ASSERT_5 0x1a
#define DICT_AF_ASSERT_6 0x1b
#define DICT_AF_UNEXPECTED_ASSERT 0x1c
#define DICT_HLTH_PING_WARN 0x1d
#define DICT_HLTH_PING_LATE 0x1e
#define DICT_HLTH_PING_WRONG_KEY 0x1f
#define DICT_HLTH_CHECK_ENABLE 0x20
#define DICT_HLTH_CHECK_PING 0x21
#define DICT_HLTH_CHECK_LOOKUP_ERROR 0x22
#define DICT_HLTH_PING_UPDATED 0x23
#define DICT_HLTH_PING_INVALID_VALUES 0x24
#define DICT_GroundInterfaceError 0x25
#define DICT_SEVERITY_FILTER_STATE 0x26
#define DICT_ID_FILTER_ENABLED 0x27
#define DICT_ID_FILTER_LIST_FULL 0x28
#define DICT_ID_FILTER_REMOVED 0x29
#define DICT_ID_FILTER_NOT_FOUND 0x2a
#define DICT_CS_SequenceLoaded 0x2d
#define DICT_CS_SequenceCanceled 0x2e
#define DICT_CS_FileReadError 0x2f
#define DICT_CS_FileInvalid 0x30
#define DICT_CS_RecordInvalid 0x31
#define DICT_CS_FileSizeError 0x32
#define DICT_CS_FileNotFound 0x33
#define DICT_CS_FileCrcFailure 0x34
#define DICT_CS_CommandComplete 0x35
#define DICT_CS_SequenceComplete 0x36
#define DICT_CS_CommandError 0x37
#define DICT_CS_InvalidMode 0x38
#define DICT_CS_RecordMismatch 0x39
#define DICT_CS_TimeBaseMismatch 0x3a
#define DICT_CS_TimeContextMismatch 0x3b
#define DICT_CS_PortSequenceStarted 0x3c
#define DICT_CS_UnexpectedCompletion 0x3d
#define DICT_CS_ModeSwitched 0x3e
#define DICT_CS_NoSequenceActive 0x3f
#define DICT_CS_SequenceValid 0x40
#define DICT_CS_SequenceTimeout 0x41
#define DICT_CS_CmdStepped 0x42
#define DICT_CS_CmdStarted 0x43
#define DICT_RateGroup1Started 0x45
#define DICT_RateGroup1CycleSlip 0x46
#define DICT_RateGroup2Started 0x47
#define DICT_RateGroup2CycleSlip 0x48
#define DICT_RateGroup3Started 0x49
#define DICT_RateGroup3CycleSlip 0x4a
#define DICT_PR_PingsDisabled 0x4c
#define DICT_PR_PingReceived 0x4d
#define DICT_DR1_OpenError 0x4f
#define DICT_DR1_ConfigError 0x50
#define DICT_DR1_WriteError 0x51
#define DICT_DR1_ReadError 0x52
#define DICT_DR1_PortOpened 0x53
#define DICT_DR1_NoBuffers 0x54
#define DICT_DR1_BufferTooSmall 0x55
#define DICT_DR2_OpenError 0x59
#define DICT_DR2_ConfigError 0x5a
#define DICT_DR2_WriteError 0x5b
#define DICT_DR2_ReadError 0x5c
#define DICT_DR2_PortOpened 0x5d
#define DICT_DR2_NoBuffers 0x5e
#define DICT_DR2_BufferTooSmall 0x5f
#define DICT_Eps_LowBattery 0x64
#define DICT_Eps_CriticallyLowBattery 0x65
#define DICT_FT_Mode 0x6e
#define DICT_FT_Frequency 0x6f
#define DICT_Gps_Error 0x78
#define DICT_PiCam_PictureTaken 0x82
#define DICT_PiCam_PictureError 0x83
#define DICT_Predi_FlightMode 0x8c
#define DICT_RckBlck_CSQ 0x96
#define DICT_RckBlck_MessageReceived 0x97
#define DICT_RckBlck_UnableToSend 0x98
#define DICT_RckBlck_MailboxCheckFail 0x9a
#define DICT_RckBlck_RingAlert 0x9b
#define DICT_RckBlck_CommandSent 0x9c
#define DICT_RckBlck_Response 0x9d
#define DICT_TempPro_LowInternalWarning 0xa0
#define DICT_TempPro_LowExternalWarning 0xa1

// Telemetry channels
#define DICT_CommandsDispatched 0x3
#define DICT_CommandErrors 0x4
#define DICT_PingLateWarnings 0x1d
#define DICT_CS_LoadCommands 0x2d
#define DICT_CS_CancelCommands 0x2e
#define DICT_CS_Errors 0x2f
#define DICT_CS_CommandsExecuted 0x30
#define DICT_CS_SequencesCompleted 0x31
#define DICT_Rg1MaxTime 0x45
#define DICT_Rg1CycleSlips 0x46
#define DICT_Rg2MaxTime 0x47
#define DICT_Rg2CycleSlips 0x48
#define DICT_Rg3MaxTime 0x49
#define DICT_Rg3CycleSlips 0x4a
#define DICT_PR_NumPings 0x4c
#define DICT_BD_Cycles 0x4e
#define DICT_DR1_BytesSent 0x4f
#define DICT_DR1_BytesRecv 0x50
#define DICT_DR2_BytesSent 0x59
#define DICT_DR2_BytesRecv 0x5a
#define DICT_Eps_BatteryVoltage 0x64
#define DICT_FT_SSDVBufferLength 0x6e
#define DICT_Gps_Position 0x78
#define DICT_PiCam_PictureCnt 0x82
#define DICT_Predi_LandingPosition 0x8c
#define DICT_RckBlck_Ch 0x96
#define DICT_TempProb_InternalTemperature 0xa0
#define DICT_TempProb_ExternalTemperature 0xa1
#define DICT_THERMOMETER_TEMP 0xb4
#define DICT_THERMOMETER_HUMI 0xb5
#define DICT_MOTIONTRACKING_ANGLES 0xbe
#define DICT_MOTIONTRACKING_GYRO 0xbf
#define DICT_MOTIONTRACKING_ACCEL 0xc0
#define DICT_MOTIONTRACKING_MAGN 0xc1
#define DICT_BAROMETER_TEMP 0xc8
#define DICT_BAROMETER_PRESS 0xc9
#define DICT_BAROMETER_ALT 0xca
#define DICT_Eps_BatteryVoltage 0x64
#define DICT_PiCam_PictureCnt 0x82

#endif
