name: Daily Aplication Build

# Builds project every day at 5:00
on:
  schedule:
    - cron: "0 3 * * *"

env:
  path: App

jobs:
  global_unit_test:
    runs-on: self-hosted
    name: Global unit tests
    steps:
      # checkout the repository with submodules
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Build the unit tests and check them one by one in the app using fprime check --all
      - name: Build and run all the unit tests
        run: |
          chmod +x ./scripts-ci/global-unit-test.sh
          ./scripts-ci/global-unit-test.sh ${{env.path}} pi
  build:
    runs-on: self-hosted
    needs: global_unit_test
    # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python
    steps:
      # checkout the repository with submodules
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Build the project (project script)
      - name: Build the project
        run: |
          chmod +x ./scripts-ci/build.sh
          ./scripts-ci/build.sh ${{env.path}} pi

      # Upload the artifact
      - name: Upload the application binaries
        uses: actions/upload-artifact@v2
        with:
          name: Application binaries
          path: ${{env.path}}/build-*
